#!/usr/bin/env python3
"""A stand-in for the GitHub CLI in the offline tests. Logs every call; never contacts anything."""
import os, sys
a = sys.argv[1:]
with open(os.environ['FAKE_LOG'], 'a') as f:
    f.write('gh\t%s\t%s\n' % ('READ' if a[:2] in (['api'], ['pr', 'view'], ['pr', 'list'], ['auth', 'status']) or (a and a[0] == 'api' and '-X' not in a) else 'MUTATE', ' '.join(a)))
if a[:2] == ['pr', 'create']:
    print('https://github.example.test/org/repo/pull/1')
elif a and a[0] == 'api':
    print('{}')
